name: "Draft new release"

on:
  workflow_dispatch:
    inputs:
      version:
        description: "Version number"
        required: true

jobs:

  draft-new-release:
    name: "Draft new release"
    runs-on: ubuntu-latest
    steps:

      - uses: actions/checkout@v3

      - name: "Create release artifacts"
        run: |
          sh dev/create-release-files.sh

      - name: "Draft new release"
        uses: softprops/action-gh-release@v1
        with:
          token: "${{ secrets.GITHUB_TOKEN }}"
          draft: true
          name: "${{ github.event.inputs.version }}"
          files: |
            releases/plugin.zip
            releases/mu-plugin.zip