name: "Draft new release"

on:
  workflow_dispatch:
    inputs:
      version:
        description: "Version name"
        required: true

jobs:

  draft-new-release:
    name: "Draft new release"
    runs-on: ubuntu-latest
    steps:

      - uses: actions/checkout@v3