name: "Draft new release"

on:
  pull_request:
  workflow_dispatch:
    inputs:
      version:
        description: "Version name"
        required: true

jobs:

  draft-new-release:
    name: "Draft new release"
    runs-on: ubuntu-latest
    steps:

      - uses: actions/checkout@v3

      - name: "Create release artifacts"
        run: |
          sh dev/create-release-files.sh

      - name: "Draft new release"
        uses: marvinpinto/action-automatic-releases@latest
        with:
          repo_token: "${{ secrets.GITHUB_TOKEN }}"
          draft: true
          title: "${{ github.event.inputs.version }}"
          files: |
            releases/plugin.zip
            releases/mu-plugin.zip